name: Update Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      run: python script.py
      env:
        PAT: ${{ secrets.ACCESS_TOKEN }}
